/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phuket_tour_audioplayer_audiotrack_MusicDecoder */

#ifndef _Included_com_phuket_tour_audioplayer_audiotrack_MusicDecoder
#define _Included_com_phuket_tour_audioplayer_audiotrack_MusicDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_phuket_tour_audioplayer_audiotrack_MusicDecoder
 * Method:    getMusicMeta
 * Signature: (Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_com_phuket_tour_audioplayer_audiotrack_MusicDecoder_getMusicMeta
  (JNIEnv *, jobject, jstring, jintArray);

/*
 * Class:     com_phuket_tour_audioplayer_audiotrack_MusicDecoder
 * Method:    openFile
 * Signature: (Ljava/lang/String;F)I
 */
JNIEXPORT jint JNICALL Java_com_phuket_tour_audioplayer_audiotrack_MusicDecoder_openFile
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     com_phuket_tour_audioplayer_audiotrack_MusicDecoder
 * Method:    readSamples
 * Signature: ([SI[I)I
 */
JNIEXPORT jint JNICALL Java_com_phuket_tour_audioplayer_audiotrack_MusicDecoder_readSamples
  (JNIEnv *, jobject, jshortArray, jint, jintArray);

/*
 * Class:     com_phuket_tour_audioplayer_audiotrack_MusicDecoder
 * Method:    closeFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_phuket_tour_audioplayer_audiotrack_MusicDecoder_closeFile
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
