/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phuket_tour_audioplayer_opensles_SoundTrackController */

#ifndef _Included_com_phuket_tour_audioplayer_opensles_SoundTrackController
#define _Included_com_phuket_tour_audioplayer_opensles_SoundTrackController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_phuket_tour_audioplayer_opensles_SoundTrackController
 * Method:    setAudioDataSource
 * Signature: (Ljava/lang/String;F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_phuket_tour_audioplayer_opensles_SoundTrackController_setAudioDataSource
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     com_phuket_tour_audioplayer_opensles_SoundTrackController
 * Method:    getAccompanySampleRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phuket_tour_audioplayer_opensles_SoundTrackController_getAccompanySampleRate
  (JNIEnv *, jobject);

/*
 * Class:     com_phuket_tour_audioplayer_opensles_SoundTrackController
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_phuket_tour_audioplayer_opensles_SoundTrackController_play
  (JNIEnv *, jobject);

/*
 * Class:     com_phuket_tour_audioplayer_opensles_SoundTrackController
 * Method:    getCurrentTimeMills
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_phuket_tour_audioplayer_opensles_SoundTrackController_getCurrentTimeMills
  (JNIEnv *, jobject);

/*
 * Class:     com_phuket_tour_audioplayer_opensles_SoundTrackController
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_phuket_tour_audioplayer_opensles_SoundTrackController_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
